# Generated by Django 5.1.1 on 2024-09-21 21:04

import core.utils
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargesFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to=core.utils.upload_to, verbose_name='Arquivo CSV de boletos')),
                ('uploadedAt', models.DateTimeField(auto_now_add=True, verbose_name='Data e hora de upload do arquivo')),
            ],
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('debtId', models.UUIDField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Id da cobrança recebido no arquivo')),
                ('name', models.CharField(max_length=40, verbose_name='Nome do sacado')),
                ('governmentId', models.CharField(max_length=48, verbose_name='Número do boleto')),
                ('email', models.EmailField(max_length=50, verbose_name='E-mail do sacado')),
                ('debtAmount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da cobrança')),
                ('debtDueDate', models.DateField(verbose_name='Data de vencimento da cobrança')),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chargesfile', verbose_name='Arquivo de origem do boleto')),
            ],
        ),
    ]
