# Generated by Django 5.1.1 on 2024-09-20 19:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChargesFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=25, verbose_name='Nome do arquivo')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de upload do arquivo')),
            ],
        ),
        migrations.CreateModel(
            name='Charge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('debt_id_from_file', models.CharField(max_length=38, verbose_name='Id da cobrança recebido no arquivo')),
                ('debtor_name', models.CharField(max_length=40, verbose_name='Nome do sacado')),
                ('government_id', models.CharField(max_length=48, verbose_name='Número do boleto')),
                ('debtor_email', models.EmailField(max_length=30, verbose_name='E-mail do sacado')),
                ('debt_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor da cobrança')),
                ('debt_due_date', models.DateField(verbose_name='Data de vencimento da cobrança')),
                ('source_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.chargesfile', verbose_name='Arquivo de origem do boleto')),
            ],
        ),
    ]
