# Generated by Django 5.1.1 on 2024-09-21 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='charge',
            name='debtId',
            field=models.CharField(max_length=38, unique=True, verbose_name='Id da cobrança recebido no arquivo'),
        ),
    ]
