# Generated by Django 5.1.1 on 2024-09-22 01:46

import django_fsm
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='charge',
            name='stage',
            field=django_fsm.FSMField(choices=[('IMPORTED', 'Imported'), ('CHECKS_PASSED', 'Checks passed'), ('CHECKS_UNPASSED', 'Checks unpassed'), ('CHARGE_GENERATED', 'Charge generated'), ('EMAIL_SENT', 'E-mail sent')], default='IMPORTED', max_length=50),
        ),
    ]
