# Generated by Django 5.1.1 on 2024-09-22 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_charge_stage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GeneratedChargeDoc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('docChargeNumber', models.CharField(max_length=20, verbose_name='Número do boleto gerado')),
                ('createdAt', models.DateTimeField(auto_now_add=True, verbose_name='Data e hora de geração do arquivo')),
                ('charge', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='charge_doc', to='core.charge')),
            ],
        ),
    ]
